import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NextAuthProvider from '@/providers/next-auth-provider';
import NextThemeProvider from '@/providers/theme-provider';
import GlobalState from '@/context';
import Header from '@/components/header';
import { ChakraProvider } from '@chakra-ui/react'
import Footer from '@/components/footer/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='dark:bg-dark dark:text-white'>
        <NextThemeProvider>
          <NextAuthProvider>
            <GlobalState>
           <ChakraProvider>
              <Header />
              {children}
            
              <Footer />
              </ChakraProvider>
            </GlobalState>
          </NextAuthProvider>
        </NextThemeProvider>
      </body>
    </html>
  )
}
